<h1><center>Laboratorio 8: ¿Superhéroe o Villano? 🦸</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Pablo Badilla
- Auxiliar: Ignacio Meza D.
- Ayudante: Constanza Peña

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Stefano Schiappacasse


### **Link de repositorio de GitHub:** `https://github.com/stefanoschiappacasse/RepoMDS7202`

### Indice 

1. [Temas a tratar](#Temas-a-tratar:)
3. [Descripcción del laboratorio](#Descripción-del-laboratorio.)
4. [Desarrollo](#Desarrollo)

# Temas a tratar

- Exploración del dataset y los resultados a través de visualizaciones interactivas usando `plotly`.
- Introducción a procesamiento del lenguaje natural.
- Clasificación en `scikit-learn`
- Uso de pipelines.

## Reglas:

- Fecha de entrega: 26/11/2021
- **Grupos de 2 personas**
- **Ausentes** deberán realizar la actividad solos. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

### Objetivos principales del laboratorio

- Aplicar las ventajas que nos ofrece crear un pipeline.
- Obtener caracteristicas desde texto.
- Visualizar el funcionamiento de clasificadores.
- Realizar una GridSearch sobre un conjunto de clasificadores.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

#Importamos librerias utiles 😸

In [1]:
# Librería Core del lab.
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split 

# Pre-procesamiento
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import CountVectorizer

# Clasifación
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Metricas de evaluación
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score

# Librería para plotear
!pip install --upgrade plotly
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Proyecciones en baja dimensionalidad: UMAP
!pip install umap-learn

# Librería para NLP
!pip install nltk
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize  
from nltk.stem import PorterStemmer
nltk.download('stopwords')
nltk.download('punkt')

  Attempting uninstall: plotly
    Found existing installation: plotly 5.4.0
    Uninstalling plotly-5.4.0:
      Successfully uninstalled plotly-5.4.0


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\stefanosch\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\stefanosch\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

# 1. ¿Quien es Bat Cow?

<p align="center">
  <img src="https://i.imgur.com/D9f1RHy.jpg" width="350">
</p>

En vez de estar desarrollando las evaluaciones correspondientes a su curso, su profesor de catedra y su auxiliar discuten acerca la alineación (héroe o villano) del personaje de ficción Bat-Cow. 

El cuerpo docente, no logra ponerse de acuerdo si el personaje es bueno, neutral o malo: el auxiliar plantea que Bat-cow posee una siniestra mirada, intrigante pero común característica de los personajes malvados. 
Por otra parte, extendiendo las ideas de Rousseau, el profesor plantea que tal como los humanos no nacen malos, no existe motivo por el cual una vaca con superpoderes deba serlo.

Sin embargo, ambos concuerdan que es difícil estimar la alineación solo usando los atributos físicos, por lo que creen el análisis debe ser complementado aún más antes de comunicarle los resultados a su estudiantado. Buscando más información, ambos sujetos se percatan de la existencia de un excelente antecedente para estimar la alineación: la historia personal de cada superhéroe o villano.

Es por esto le solicitan que construya y optimice un clasificador basado en texto el cual analice la alineación de cada personaje basado en su historia personal.

Para este laboratorio deben trabajar con los datos `df_comics.csv` y `comics_no_label.csv` subidos a u-cursos. El primero es un conjunto de datos que les servirá para entrenar un modelo de clasificación, mientras que el segundo es un dataset con personajes de ficción no etiquetados a predecir (sí, aquí está la misteriosa Batcow).

Para comenzar cargue los dataset señalados y visualice a través de un head los atributos que poseen cada uno de los dataset.


In [2]:
df_comics = pd.read_csv('df_comics.csv')
df_comics_no_label = pd.read_csv('comics_no_label.csv')
df_comics = df_comics.dropna(subset=['history_text']) # eliminar ejemplos sin historia

In [3]:
# queda a labor de su equipo hacer el análisis exploratorio
df_comics.head()

Unnamed: 0          name               real_name               full_name  \
0           0       3-D Man     Delroy Garrett, Jr.     Delroy Garrett, Jr.   
1           2        A-Bomb  Richard Milhouse Jones  Richard Milhouse Jones   
2           3            Aa                      Aa                     NaN   
3           4    Aaron Cash              Aaron Cash              Aaron Cash   
4           5  Aayla Secura            Aayla Secura                     NaN   

  overall_score                                       history_text  \
0             6  Delroy Garrett, Jr. grew up to become a track ...   
1            20   Richard "Rick" Jones was orphaned at a young ...   
2            12  Aa is one of the more passive members of the P...   
3             5  Aaron Cash is the head of security at Arkham A...   
4             8  ayla Secura was a Rutian Twi'lek Jedi Knight (...   

                                         powers_text  intelligence_score  \
0                                                NaN                  85   
1    On rare occasions, and through unusual circu...                  80   
2                                                NaN                  80   
3                                                NaN                  80   
4                                                NaN                  90   

   strength_score  speed_score  ...  has_flight  has_accelerated_healing  \
0              30           60  ...         0.0                      0.0   
1             100           80  ...         0.0                      1.0   
2              50           55  ...         0.0                      0.0   
3              10           25  ...         0.0                      0.0   
4              40           45  ...         0.0                      1.0   

   has_weapons_master has_intelligence has_reflexes has_super_speed  \
0                 0.0              0.0          0.0             1.0   
1                 0.0              0.0          1.0             1.0   
2                 0.0              0.0          0.0             0.0   
3                 1.0              0.0          0.0             0.0   
4                 0.0              0.0          0.0             0.0   

  has_durability has_stamina has_agility has_super_strength  
0            0.0         0.0         0.0                1.0  
1            1.0         1.0         1.0                1.0  
2            0.0         0.0         0.0                0.0  
3            0.0         0.0         0.0                0.0  
4            0.0         0.0         1.0                0.0  

[5 rows x 82 columns]

In [4]:
# queda a labor de su equipo hacer el análisis exploratorio
df_comics_no_label.head()

Unnamed: 0              name    real_name        full_name overall_score  \
0           1     514A (Gotham)  Bruce Wayne              NaN            10   
1          14        Ace Morgan  Kyle Morgan              NaN             7   
2          17             A'dal          NaN              NaN             7   
3          27  Agent Zero (FOX)  David North              NaN             6   
4          31        Ajax (FOX)      Francis  Francis Freeman             7   

                                        history_text  \
0  He was one of the many prisoners of Indian Hil...   
1                                                NaN   
2  As with most of the naaru, little is known of ...   
3  During mid-late 1973, Zero was a member of Tea...   
4  Ajax (born Francis Freeman) was a human who ga...   

                                         powers_text  intelligence_score  \
0                                                NaN                 100   
1  Aviation:  Ace is an extremely skilled pilot, ...                  85   
2                                                NaN                  85   
3  Zero can absorb kinetic energy to further incr...                  90   
4  Ajax has claimed that the procedure to obtain ...                  85   

   strength_score  speed_score  ...  has_flight  has_accelerated_healing  \
0              20           30  ...         0.0                      0.0   
1              20           65  ...         0.0                      0.0   
2              30           70  ...         0.0                      0.0   
3              10           25  ...         0.0                      0.0   
4              25           45  ...         0.0                      0.0   

   has_weapons_master has_intelligence has_reflexes has_super_speed  \
0                 0.0              0.0          1.0             0.0   
1                 1.0              1.0          1.0             0.0   
2                 0.0              0.0          0.0             0.0   
3                 0.0              0.0          1.0             0.0   
4                 1.0              1.0          1.0             0.0   

  has_durability has_stamina has_agility  has_super_strength  
0            1.0         0.0         0.0                 1.0  
1            0.0         1.0         1.0                 0.0  
2            0.0         0.0         0.0                 0.0  
3            0.0         0.0         1.0                 0.0  
4            1.0         0.0         0.0                 1.0  

[5 rows x 82 columns]

## 1.1 Obtención de Features y Bag of Words

<p align="center">
  <img src="https://media0.giphy.com/media/eIUpSyzwGp0YhAMTKr/200.gif" width="300">
</p>

Primero que todo, deben obtener un vector de características del atributo `history_text`, utilizando `bag of words`. En este atributo se presenta una breve descripción de la historia de cada uno de los personajes de ficción presentes en el dataset. 

Pero... antes de empezar, ¿Que es `bag of words`?...

`bag of words` es un modelo de conteo utilizado en Procesamiento de Lenguaje Natural (NLP) que tiene como objetivo generar una representación vectorial (vector de características en nuestro cas) para cada documento a través del conteo de las palabras que contienen. 

La siguiente figura muestra un ejemplo de `bag of words` en acción:

<p align="center">
  <img src="https://user.oc-static.com/upload/2020/10/23/16034397439042_surfin%20bird%20bow.png" width="500">
</p>

Como pueden ver, el modelo de `bag of words` no resulta tan complicado, ¿pero cómo lo aplicamos en python?. 

Como podrán darse cuenta del ejemplo anterior, para facilitar el conteo será necesario transformar cada uno de los documentos en vectores, donde cada una de las posiciones posee un carácter. Este proceso es conocido como **tokenización** y lo podemos realizar de la siguiente forma:

In [5]:
docs = ['The teacher rocks like a good rock & roll',
             'the rock is the best actor in the world']


docs_tokenizados = [word_tokenize(doc)  for doc in docs]
docs_tokenizados

[['The', 'teacher', 'rocks', 'like', 'a', 'good', 'rock', '&', 'roll'],
 ['the', 'rock', 'is', 'the', 'best', 'actor', 'in', 'the', 'world']]

Podemos mejorar un poco más el proceso de tokenización agregando 

- Stemming:  Definimos Stemming como un algoritmo basado en reglas que transforma las palabras a una forma general. Un ejemplo de stemming, es el siguiente:
- Eliminación de Stopwords: Eliminación de palabras muy frecuentes que entorpecen la clasificación (por ejemplo, el, la los, la, etc...)

<p align="center">
  <img src="https://devopedia.org/images/article/218/8583.1569386710.png" width="300">
</p>


In [6]:
# Definimos algunas stopword que queremos que sean eliminadas
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words = stopwords.words('spanish')

# Definimos un tokenizador con Stemming
class StemmerTokenizer:
    def __init__(self):
        self.ps = PorterStemmer()
    def __call__(self, doc):
        doc_tok = word_tokenize(doc)
        doc_tok = [t for t in doc_tok if t not in stop_words]
        return [self.ps.stem(t) for t in doc_tok]

# Inicializamos tokenizador
tokenizador = StemmerTokenizer()

# Creamos algunos documentos
docs = ['The teacher rocks like a good rock & roll',
        'the rock is the best actor in the world',
        'New York is a beautiful city']

# Obtenemos el token del primer documento
[tokenizador(doc) for doc in docs]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\stefanosch\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


[['the', 'teacher', 'rock', 'like', 'good', 'rock', '&', 'roll'],
 ['the', 'rock', 'is', 'the', 'best', 'actor', 'in', 'the', 'world'],
 ['new', 'york', 'is', 'beauti', 'citi']]

In [7]:
# Comparación con el caso anterior
docs_tokenizados = [word_tokenize(doc) for doc in docs]
docs_tokenizados

[['The', 'teacher', 'rocks', 'like', 'a', 'good', 'rock', '&', 'roll'],
 ['the', 'rock', 'is', 'the', 'best', 'actor', 'in', 'the', 'world'],
 ['New', 'York', 'is', 'a', 'beautiful', 'city']]

#### Al Estilo Scikit

Scikit implementa `bag of words` a través de la clase `CountVectorizer()` la cual contiene muchas opciones para mejorar la tokenización.

In [8]:
bow = CountVectorizer(tokenizer= StemmerTokenizer())
df = bow.fit_transform(docs)

pd.DataFrame(df.toarray(), columns=bow.get_feature_names_out())

&  actor  beauti  best  citi  good  in  is  like  new  rock  roll  teacher  \
0  1      0       0     0     0     1   0   0     1    0     2     1        1   
1  0      1       0     1     0     0   1   1     0    0     1     0        0   
2  0      0       1     0     1     0   0   1     0    1     0     0        0   

   the  world  york  
0    1      0     0  
1    3      1     0  
2    0      0     1

Una de las cosas más interesantes que provee son el use de n-gramas, los cuales, en palabras simples, son conjuntos de n-palabras que se concatenan entre si y que se consideran como tokens separados. 

Pensemos en `Nueva York`. Cuando se tokeniza Nueva York, se generan dos tokens independientes que a simple vista no tienen relación: `Nueva` `York`.
Al usar n-gramas (en un rango min=1,max=2) , generamos tanto `Nueva` y `York` como también `Nueva York` como un token independiente.

In [9]:
bow = CountVectorizer(tokenizer= StemmerTokenizer(), ngram_range=(1,2))
df = bow.fit_transform(docs)

pd.DataFrame(df.toarray(), columns=bow.get_feature_names_out())

&  & roll  actor  actor in  beauti  beauti citi  best  best actor  citi  \
0  1       1      0         0       0            0     0           0     0   
1  0       0      1         1       0            0     1           1     0   
2  0       0      0         0       1            1     0           0     1   

   good  ...  teacher  teacher rock  the  the best  the rock  the teacher  \
0     1  ...        1             1    1         0         0            1   
1     0  ...        0             0    3         1         1            0   
2     0  ...        0             0    0         0         0            0   

   the world  world  york  york is  
0          0      0     0        0  
1          1      1     0        0  
2          0      0     1        1  

[3 rows x 35 columns]

De los resultados, podemos ver que generamos vectores de conteo para cada una de las palabras que conforman el corpus.  Un punto extra que se agrega en esta obtención de frecuencias son los bigramas, que básicamente son el conjunto de palabras de tamaño de aparecen juntas en el texto.

## Codificando los Super{heroes, villanos}  [0.5 Puntos]

<p align="center">
  <img src="https://c.tenor.com/LkQzw7k5DV4AAAAd/anime-hacking.gif" width="300">
</p>

Conociendo ahora que es el proceso de `bag of words`, aplique este modelo de obtención de caracteristicas de la siguiente forma en un pipeline:

- Utilice el tokenizador entregado.
- Obtenga caracteristicas de los unigramas y bigramas del texto (tal como el ejemplo).

```python
bog = CountVectorizer(tokenizer= StemmerTokenizer(),`
                      ngram_range=(1,2) # Este punto es opcional y es para generar bigramas
                      )
```

Finalmente, aplique `MinMaxScaler()` sobre `atributos_de_interes` y concatene el valor obtenido con el matriz de caracteristicas obtenidas con bag of words.

```python
atributos_de_interes = ['intelligence_score', 'strength_score', 'speed_score', 'durability_score', 'power_score', 'combat_score']
```

No es necesario que obtenga un dataframe en concreto con las características solicitadas. Se le recomienda generar un `ColumnTransformer()` para aplicar las transformaciones solicitadas en un pipeline.

**To-Do:**
- [ ] Obtener a traves de bag of words caracteristicas del resumen de historia de cada personaje.
- [ ] Aplicar MinMaxScaler sobre los atributos de interes.

**Respuesta:**

In [10]:
#### Código aquí ####
#Vectorizer
bog = CountVectorizer(tokenizer= StemmerTokenizer(),
                      ngram_range=(1,2)
                      )
#Atributos de interés
atributos_de_interes = ['intelligence_score', 'strength_score', 'speed_score', 
                        'durability_score', 'power_score', 'combat_score']
#Transformación minmax
transformaciones = ColumnTransformer(transformers= 
    [('minMax', MinMaxScaler(),atributos_de_interes),
     ('bog', bog, 'history_text')],
                           remainder = 'drop'
)

In [13]:
X_train

intelligence_score  strength_score  speed_score  durability_score  \
940                  80              40           70                70   
859                  75              35           25                40   
900                  80              50           35                30   
320                  85              80           90                95   
366                  85              40           65                60   
..                  ...             ...          ...               ...   
203                 100              10           25                30   
72                   50              20           40                45   
699                  90              20           25                40   
429                  75              55           70                70   
288                  90              10           40                40   

     power_score  combat_score  \
940          100            85   
859           30            75   
900           35            55   
320          100           100   
366           65            65   
..           ...           ...   
203           60            30   
72           100            95   
699           15            70   
429           65            95   
288           70           100   

                                          history_text  
940  Percy was born to Sally Jackson and Poseidon. ...  
859   Spector's father, a rabbi, managed to escape ...  
900  Nicole "Niki" Sanders is a former casino worke...  
320  Dante is the central protagonist of the Devil ...  
366  Dr. Simon Ecks is a scientist who discovered t...  
..                                                 ...  
203  Brainiac 5 is a member of the Legion of Super-...  
72   When Daddy No Legs lead the Ninja into the Pit...  
699   Very little is known about the Kingpin before...  
429  Fandral was a highly respected Asgardian warri...  
288  Ratonhnhaké:ton who later adopted the name Con...  

[1028 rows x 7 columns]

In [14]:
transformaciones.fit_transform(X_train).toarray()

array([[0.8 , 0.4 , 0.7 , ..., 0.  , 0.  , 0.  ],
       [0.75, 0.35, 0.25, ..., 0.  , 0.  , 0.  ],
       [0.8 , 0.5 , 0.35, ..., 0.  , 0.  , 0.  ],
       ...,
       [0.9 , 0.2 , 0.25, ..., 0.  , 0.  , 0.  ],
       [0.75, 0.55, 0.7 , ..., 0.  , 0.  , 0.  ],
       [0.9 , 0.1 , 0.4 , ..., 0.  , 0.  , 0.  ]])

## 1.2 Diseño de Baseline y  Primer Entrenamiento  [1 Puntos]


<p align="center">
  <img src="https://pa1.narvii.com/6374/9eaec1b7bf9157334151452a669516f9a78b954c_hq.gif" width="300">
</p>


Genere un Pipeline con las caracteristicas solicitadas en la sección 1.1, un selector de mejores features `SelectPercentile` con métrica `f_classif` y percentile=90 y un clasificador `MultinomialNB()` por defecto.

Luego, separe el conjunto de datos en un conjunto de entrenamiento y prueba, donde las etiquetas estará dado por el atributo `alignment`. 

Finalmente entrene el modelo y reporte el desempeño con un `classification_report`. ¿ Nos recomendaría predecir la alineación de BatCow con este clasificador?.

**To-DO:**
- [ ] Realizar un pipeline con las caracteristicas solicitadas en 1.1 y aplicar un clasificador  `MultinomialNB()`.
- [ ] Entrenar el pipeline y comentar los resultados.

**Respuesta:**

In [11]:
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, confusion_matrix

#función para mostrar el desempeño del modelo.
def train_and_evaluate(pipe,
                       X_train,
                       y_train,
                       X_test,
                       y_test,
                       print_=True
                       ):

    # notar que los datasets son parámetros por defecto.
    
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    if print_:
        print('Matriz de confusión: \n')
        print(confusion_matrix(y_test, y_pred, labels=pipe.classes_))
        print('\nReporte de Clasificación: \n')
        print(classification_report(y_test, y_pred, target_names=pipe.classes_), )
    
    return f1_score(y_test, y_pred, average='weighted')

#nombre de columnas de interés
featuresNames = atributos_de_interes + ['history_text']
#dataset de atributos
features = df_comics.loc[:, featuresNames]
#atributo a predecir
labels = df_comics['alignment']
#separación conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(features,
                                                    labels,
                                                    test_size=0.2,
                                                    random_state=50,
                                                    shuffle=True,
                                                    stratify=labels)

#creación del pipeline
selection_pipeline = Pipeline(steps=[
    ("transformaciones", transformaciones),
    ("seleccion", SelectPercentile(f_classif, percentile=90)),
    ("clasificador", MultinomialNB()),
])

#entrenamiento y evaluación
train_and_evaluate(selection_pipeline,
                  X_train,
                  y_train,
                  X_test,
                  y_test)

Matriz de confusión: 

[[  7  79   0]
 [  4 144   0]
 [  2  20   1]]

Reporte de Clasificación: 

              precision    recall  f1-score   support

         Bad       0.54      0.08      0.14        86
        Good       0.59      0.97      0.74       148
     Neutral       1.00      0.04      0.08        23

    accuracy                           0.59       257
   macro avg       0.71      0.37      0.32       257
weighted avg       0.61      0.59      0.48       257



0.4789535819146615

Observando los resultados, podemos notar que en general el modelo no se comporta muy bien identificando el `alignment` de los personajes. Con la clase que mejor se comporta es con los personajes `Good`, teniendo un f1 de 0.74, que es la clase que posee mayores ejemplos en el dataset. Llama la atención que sólo predijo una observación de la clase `Neutral`, y que el 95% de sus predicciones hayan sido de la clase `Good`. Esto demuestra que en general el modelo se sobreajustó a la clase mayoritaria y termina apuntando casi todas sus predicciones hacia ella. 

## 1.3 Busqueda del Mejor Modelo con Grid Search [4 Puntos]

<p align="center">
  <img src="https://media1.tenor.com/images/70fdfeea52a8e2e4505498c230a0d2f9/tenor.gif?itemid=5134219" width="250">
</p>

No conformes con el rendimiento obtenido en la sección 1.2, el cuerpo docente les pide que realicen un **`HalvingGridSearchCV`** con diferentes parámetros para mejorar el rendimiento de la clasificación. Para esto, se le solicita que defina:

- Dos clasificadores distintos en donde varie sus parámetros. Se le recomienda utilizar `LogisticRegression()` y `RandomForestClassifier()`.
- Modificar `n-gram` range del `CountVectorizer` probando `(1,1), (1,2) y (1,3)`. 
- Selección de las mejores columnas para la clasificación con `SelectPercentile` en los percentiles `[20, 40, 60, 80]` (puede usar la métrica que usted quiera).

A continuación, un ejemplo de parametros para GridSearch para una búsqueda de 3 clasificadores distintos:

```python
params = [
       # clasificador 1 + hiperparámetros
       {'clf': classificator1(),
        'clf__penalty': ['ovr'],
        'clf__multi_class': ['liblinear']},
       # clasificador 1 + hiperparámetros    
       {'clf': classificator2(),
        'clf__n_estimators': [200]},
       # clasificador 1 + hiperparámetros
       {'clf': classificator3(),
        ...
       }
       ]
```

**Nota 1**: Puede ver los parámetros modificables aplicando el método get_params() sobre su pipeline.

**Nota 2**: Recuerde inicializar los clasificadores con un random state definido.

**Nota 3**: Puede usar en `HalvingGridSearchCV` el parámetro `verbose=10` para ver que GridSearch le indique el estado de su ejecución.

**Nota 3:** El GridSearch puede tomar tiempos de búsqueda exorbitantes, por lo que se le recomienda no agrandar mucho el espacio de búsqueda, dejar corriendo el código y tomarse un tecito.

**Respuesta:**

In [23]:
from sklearn.feature_selection import f_classif, mutual_info_classif
from sklearn.experimental import enable_halving_search_cv  # noqa
from sklearn.model_selection import HalvingGridSearchCV

#pipe para la búsqueda de grilla
selection_pipeline = Pipeline(steps=[
    ("Preprocessing", transformaciones),
    ("Selection", SelectPercentile()),
    ('clf', LogisticRegression())
])

#grilla de hiperparámetros
param_grid = [{
    'Preprocessing__bog__ngram_range':[(1,1), (1,2), (1,3)],
    "Selection__percentile": [20,40,60,80],
    "Selection__score_func": [f_classif],
    'clf': [LogisticRegression(random_state = 102)],
    'clf__penalty': ['l2', 'none'],
    'clf__multi_class': ['auto', 'multinomial']
},
    {'Preprocessing__bog__ngram_range':[(1,1), (1,2), (1,3)],
    "Selection__percentile": [20,40,60,80],
    "Selection__score_func": [f_classif],
    'clf': [RandomForestClassifier(random_state = 102)],
    'clf__n_estimators': [100,500,1000,2000],
    'clf__max_depth': [4, 8,15]}
]

#Creación y búsqueda de hiperparámetros
hgs = HalvingGridSearchCV(selection_pipeline, param_grid, n_jobs = -1, verbose = 10)
train_and_evaluate(hgs, X_train, y_train, X_test, y_test)

n_iterations: 4
n_required_iterations: 5
n_possible_iterations: 4
min_resources_: 30
max_resources_: 1028
aggressive_elimination: False
factor: 3
----------
iter: 0
n_candidates: 192
n_resources: 30
Fitting 5 folds for each of 192 candidates, totalling 960 fits
----------
iter: 1
n_candidates: 64
n_resources: 90
Fitting 5 folds for each of 64 candidates, totalling 320 fits
----------
iter: 2
n_candidates: 22
n_resources: 270
Fitting 5 folds for each of 22 candidates, totalling 110 fits
----------
iter: 3
n_candidates: 8
n_resources: 810
Fitting 5 folds for each of 8 candidates, totalling 40 fits


D:\anaconda3\envs\MDS7202\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Matriz de confusión: 

[[ 39  47   0]
 [ 13 135   0]
 [  7  14   2]]

Reporte de Clasificación: 

              precision    recall  f1-score   support

         Bad       0.66      0.45      0.54        86
        Good       0.69      0.91      0.78       148
     Neutral       1.00      0.09      0.16        23

    accuracy                           0.68       257
   macro avg       0.78      0.48      0.49       257
weighted avg       0.71      0.68      0.65       257



0.6463224111408236

In [25]:
hgs.best_params_

{'Preprocessing__bog__ngram_range': (1, 3),
 'Selection__percentile': 40,
 'Selection__score_func': <function sklearn.feature_selection._univariate_selection.f_classif(X, y)>,
 'clf': LogisticRegression(random_state=102),
 'clf__multi_class': 'auto',
 'clf__penalty': 'l2'}

Interesante observar que el mejor clasificador fue la regresión logística, utilizando un penalty `l2`, seleccionando el 40% de los atributos y usando 3-gramas, obteniendo un `weighted avg f1-score` de 0.65 y un `accuracy de 0.68`. En general el modelo posee mejor desempeño con los personajes que son `Good`, al igual que el modelo multinomial, sin embargo ahora su porcentaje de predicción de la clase mayoritaria es del 76% y no el 95% como en el caso anterior. Nuevamente tenemos problemas con la clase minoritaria `Neutral`, en donde se observan sólo 2 predicciones hacia esa. Donde más marca la diferencia este modelo por sobre el anterior, es en la clase `Bad`, en donde su recall aumentó en más de 5 veces y su precisión en un 12%. Esto demuestra, que hacer pruebas con distintos hiperparámetros permite buscar la combinación que entrega mejores resultados para el problema planteado.

## 1.4 Predicción del datos sin etiquetado  [0.5 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/DolotxUUYAAbg7f.jpg" width="350">
</p>


LLego el momento de predecir 
`Vergil`, `Gorilla Girl` y `Batcow`


**Nota:** Recuerde que pueden existir campos vacios en `history_text`, por lo que se les recomienda borrar los nan.

**Respuesta:**

In [68]:
etiquetas = hgs.predict(df_comics_no_label.dropna(subset = ['history_text']))
dfConEtiquetas = pd.concat([df_comics_no_label.dropna(subset = ['history_text']).reset_index(drop = True),
                            pd.Series(etiquetas, name = 'Etiqueta')], axis = 1)
dfConEtiquetas.shape

(76, 83)

In [69]:
dfConEtiquetas.loc[dfConEtiquetas['name'].isin(['Vergil', 'Batcow', 'Gorilla Girl']), ['name', 'Etiqueta']]

name Etiqueta
14        Batcow     Good
37  Gorilla Girl     Good
71        Vergil     Good
75        Batcow     Good

Podemos observar que el modelo etiqueta a los tres personajes como `Good`. Espero esté en lo cierto.

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana y que **los días de atraso no se pueden utilizar para entregas de lab, solo para tareas**. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media1.tenor.com/images/fb5bf7cc5a4acb91b4177672886a88ba/tenor.gif?itemid=5591338">
</p>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>